name:                MyBot
version:             0.1.0.0
github:              "githubuser/MyBot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MyBot#readme>

dependencies:
- base >= 4.7 && < 5
- dotenv
- wreq
- text
- lens
- bytestring
- aeson
- lens-aeson
- wuss
- websockets
- network-uri

library:
  source-dirs: src

executables:
  MyBot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MyBot

tests:
  MyBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MyBot
